### ISSUE TITLE
Fork it on github needed

### ISSUE THREAD

**Issue by codeliner** [sandrokeil/bookdown-template#2]
Is it possible to add a "Fork it on github" banner/btn that brings the user to the documentation repo or if they view a component docs then to the component repo?

Is it possible to add "metadata" to a page and then read that metadata in a view helper? This way we can set the document repo link or even the link to the concrete markdown file  as metadata and easily use that info for the fork button.

**Comment by sandrokeil** [comment]
We have some possibilites in the [main.php](https://github.com/sandrokeil/bookdown-template/blob/master/template/main.php) file and we can override other template files and can even use Aura View Helper.

The problem here is if we use this repo to aggregate other docs from other repos.

You want to get for each content bookdown json file e.g. service-bus on these pages a fork on GitHub Button right? Maybe we could at something like this to our [nav.php](https://github.com/sandrokeil/bookdown-template/blob/master/template/nav.php) or to the footer. 

Has you some ideas @tobiju ?

**Comment by tobiju** [comment]
@codeliner you can add custom properties to the ```bookdown.json``` file to use them in a view helper. What you want to realize is a ```github repository view helper```, this could look like the following example configuration.

bookdown.json
```json
'github': {
    'link': 'https://github.com/somerepo'
    'imagePath': 'ImagePath.png',
    'svg': '....' 
}
```

**Comment by codeliner** [comment]
@tobiju Here is my view helper: https://github.com/prooph/proophessor/pull/69

It did not work with bookdown.json because I was only able to use a custom config in the root bookdown.json but I need that repo link for every remote repository. Anyway, the IndexConfig gave me all I need ;)

**Comment by sandrokeil** [comment]
Cool :+1:

**Comment by tobiju** [comment]
👍
